spring:
  application:
    name: feign-client
server:
  port: 18766

eureka:
  client:
    serviceUrl:
      defaultZone: http://123.59.17.115:18761/eureka/
      
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    feign-client:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000