eureka:
  client:
    serviceUrl:
      defaultZone: http://123.59.17.115:18761/eureka/
server:
  port: 18765
spring:
  application:
    name: zuul-client
zuul:
  routes:
    feignapi:
      path: /feignapi/**
      serviceId: feign-client
      stripPrefix: true #有该字段，请求的"feignapi"会被转发到
zuul.prefix: /v1  #加个前缀

hystrix:
  command:
    feign-client:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 